### ISSUE TITLE
Handling failure based on the task status

### ISSUE THREAD

**Issue by vishnukadi** [xebialabs-community/xlr-jython-code-snippets#1]
We have a task within the template that fetches the status of a Feature from Rally. The task status/output is stored in a variable and possible values for the status are Ready, Undefined and Blocked. 
If the status is 'Ready', it has to move to the subsequent task. If it's anything other than 'Ready' (like 'Blocked' or 'undefined') the task has to fail.

I am looking for a jython code snippet to achieve this using failure handler.

**Comment by jpflug** [comment]
Hello, this community repository is really not the place to pose questions in this format. You should submit a ticket to https://support.xebialabs.com/hc/en-us/requests/new so that we can track your question and ensure you get the best quality answer possible. 

Thanks!
